CREATE TABLE IF NOT EXISTS items (
	id INTEGER PRIMARY KEY,
	name TEXT COLLATE NOCASE,
    examine TEXT COLLATE NOCASE,
	resize_x INTEGER,
	resize_y INTEGER,
	resize_z INTEGER,
	xan2d INTEGER,
	yan2d INTEGER,
	zan2d INTEGER,
	cost INTEGER,
	is_tradable TEXT,
	stackable INTEGER,
	inventory_model INTEGER,
	wear_pos_1 INTEGER,
	wear_pos_2 INTEGER,
	wear_pos_3 INTEGER,
	members TEXT,
	zoom_2d INTEGER,
	x_offset_2d INTEGER,
	y_offset_2d INTEGER,
	ambient INTEGER,
	contrast INTEGER,
	options TEXT,
	interface_options TEXT,
	male_model_0 INTEGER,
	male_model_1 INTEGER,
	male_model_2 INTEGER,
	male_offset INTEGER,
	male_head_model INTEGER,
	male_head_model_2 INTEGER,
	female_model_0 INTEGER,
	female_model_1 INTEGER,
	female_model_2 INTEGER,
	female_offset INTEGER,
	female_head_model INTEGER,
	female_head_model_2 INTEGER,
	noted_id INTEGER,
	noted_template INTEGER,
	team INTEGER,
	weight INTEGER,
	shift_click_drop_index INTEGER,
	bought_id INTEGER,
	bought_template_id INTEGER,
	placeholder_id INTEGER,
	placeholder_template_id INTEGER,
	color_find TEXT,
	color_replace TEXT,
	params TEXT,
	count_co TEXT,
	count_obj TEXT,
	texture_find TEXT,
	texture_replace TEXT,
	category INTEGER
);

CREATE TABLE IF NOT EXISTS npcs (
	id INTEGER PRIMARY KEY,
	name TEXT COLLATE NOCASE,
	size INTEGER,
	models TEXT,
	chathead_models TEXT,
	standing_animation INTEGER, 
	idle_rotate_left_animation INTEGER,
	idle_rotate_right_animation INTEGER,
	walking_animation INTEGER,
	rotate_left_animation INTEGER,
	rotate_right_animation INTEGER,
	run_animation INTEGER,
	run_rotate_180_animation INTEGER,
	run_rotate_left_animation INTEGER,
	run_rotate_right_animation INTEGER,
	crawl_animation INTEGER,
	crawl_rotate_180_animation INTEGER,
	crawl_rotate_left_animation INTEGER,
	crawl_rotate_right_animation INTEGER,
	actions TEXT,
	is_minimap_visible TEXT,
	combat_level INTEGER,
	width_scale INTEGER,
	height_scale INTEGER,
	has_render_priority TEXT,
	ambient INTEGER,
	contrast INTEGER,
	head_icon_sprite_index TEXT,
	head_icon_archive_ids TEXT,
	rotation_speed INTEGER,
	varbit_id INTEGER,
	varp_index INTEGER,
	is_interactable TEXT,
	rotation_flag TEXT,
	is_pet TEXT,
	configs TEXT,
	params TEXT,
	category INTEGER,
	recolor_to_find TEXT,
	recolor_to_replace TEXT,
	retexture_to_find TEXT,
	retexture_to_replace TEXT,
	is_follower TEXT,
	low_priority_follower_ops TEXT
);

CREATE TABLE IF NOT EXISTS objects (
	id INTEGER PRIMARY KEY,
	name TEXT COLLATE NOCASE,
	decor_displacement INTEGER,
	is_hollow TEXT,
	object_models TEXT,
	object_types TEXT,
	map_area_id INTEGER,
	size_x INTEGER,
	size_y INTEGER,
	offset_x INTEGER,
    offset_y INTEGER,
    offset_height INTEGER,
    merge_normals TEXT,
	wall_or_door INTEGER,
	animation_id INTEGER,
	varbit_id INTEGER,
	ambient INTEGER,
	contrast INTEGER,
	recolor_to_find TEXT, 
	recolor_to_replace TEXT,
	retexture_to_find TEXT,
	texture_to_replace TEXT,
	actions TEXT,
	interact_type INTEGER,
	map_scene_id INTEGER,
	blocking_mask INTEGER,
	shadow TEXT,
	model_size_x INTEGER,
    model_size_y INTEGER,
	model_size_height INTEGER,
	object_id INTEGER,
	obstructs_ground TEXT,
	contoured_ground INTEGER,
	supports_items INTEGER,
	config_change_dest TEXT,
	category INTEGER,
	is_rotated TEXT,
	varp_id INTEGER,
	ambient_sound_id INTEGER,
	ambient_sound_ids TEXT,
	ambient_sound_retain INTEGER,
	ambient_sound_distance INTEGER,
	ambient_sound_change_ticks_min INTEGER,
	ambient_sound_change_ticks_max INTEGER,
	params TEXT,
	a_bool_2111 TEXT,
	blocks_projectile TEXT,
	randomize_anim_start TEXT
);