package main

var ItemQueryTypes = map[string]int{
	"id":                      1, //int, exact match
	"name":                    2, // string, fuzzy match
	"examine":                 2,
	"resize_x":                1,
	"resize_y":                1,
	"resize_z":                1,
	"xan2d":                   1,
	"yan2d":                   1,
	"zan2d":                   1,
	"cost":                    1,
	"is_tradable":             1, // string but needs exact match
	"stackable":               1,
	"inventory_model":         1,
	"wear_pos_1":              1,
	"wear_pos_2":              1,
	"wear_pos_3":              1,
	"members":                 3,
	"zoom_2d":                 1,
	"x_offset_2d":             1,
	"y_offset_2d":             1,
	"ambient":                 1,
	"contrast":                1,
	"options":                 2,
	"interface_options":       2,
	"male_model_0":            1,
	"male_model_1":            1,
	"male_model_2":            1,
	"male_offset":             1,
	"male_head_model":         1,
	"male_head_model_2":       1,
	"female_model_0":          1,
	"female_model_1":          1,
	"female_model_2":          1,
	"female_offset":           1,
	"female_head_model":       1,
	"female_head_model_2":     1,
	"noted_id":                1,
	"noted_template":          1,
	"team":                    1,
	"weight":                  1,
	"shift_click_drop_index":  1,
	"bought_id":               1,
	"bought_template_id":      1,
	"placeholder_id":          1,
	"placeholder_template_id": 1,
	"color_find":              3, // String with fuzzy match but special case of exact match if query is null first
	"color_replace":           3,
	"params":                  3,
	"count_co":                3,
	"count_obj":               3,
	"texture_find":            3,
	"texture_replace":         3,
	"category":                1,
}

var NPCQueryTypes = map[string]int{
	"id":                           1,
	"name":                         2,
	"size":                         1,
	"models":                       2,
	"chathead_models":              2,
	"standing_animation":           1,
	"idle_rotate_left_animation":   1,
	"idle_rotate_right_animation":  1,
	"walking_animation":            1,
	"rotate_left_animation":        1,
	"rotate_right_animation":       1,
	"run_animation":                1,
	"run_rotate_180_animation":     1,
	"run_rotate_left_animation":    1,
	"run_rotate_right_animation":   1,
	"crawl_animation":              1,
	"crawl_rotate_180_animation":   1,
	"crawl_rotate_left_animation":  1,
	"crawl_rotate_right_animation": 1,
	"actions":                      2,
	"is_minimap_visible":           3,
	"combat_level":                 1,
	"width_scale":                  1,
	"height_scale":                 1,
	"has_render_priority":          3,
	"ambient":                      1,
	"contrast":                     1,
	"head_icon_sprite_index":       2,
	"head_icon_archive_ids":        2,
	"rotation_speed":               1,
	"varbit_id":                    1,
	"varp_index":                   1,
	"is_interactable":              3,
	"rotation_flag":                3,
	"is_pet":                       3,
	"configs":                      2,
	"params":                       2,
	"category":                     1,
	"recolor_to_find":              2,
	"recolor_to_replace":           2,
	"retexture_to_find":            2,
	"retexture_to_replace":         2,
	"is_follower":                  3,
	"low_priority_follower_ops":    3,
}

var ObjectQueryTypes = map[string]int{
	"id":                             1,
	"name":                           2,
	"decor_displacement":             1,
	"is_hollow":                      3,
	"object_models":                  2,
	"object_types":                   2,
	"map_area_id":                    1,
	"size_x":                         1,
	"size_y":                         1,
	"offset_x":                       1,
	"offset_y":                       1,
	"offset_height":                  1,
	"merge_normals":                  3,
	"wall_or_door":                   1,
	"animation_id":                   1,
	"varbit_id":                      1,
	"ambient":                        1,
	"contrast":                       1,
	"recolor_to_find":                2,
	"recolor_to_replace":             2,
	"retexture_to_find":              2,
	"texture_to_replace":             2,
	"actions":                        2,
	"interact_type":                  1,
	"map_scene_id":                   1,
	"blocking_mask":                  1,
	"shadow":                         3,
	"model_size_x":                   1,
	"model_size_y":                   1,
	"model_size_height":              1,
	"object_id":                      1,
	"obstructs_ground":               3,
	"contoured_ground":               1,
	"supports_items":                 1,
	"config_change_dest":             2,
	"category":                       1,
	"is_rotated":                     3,
	"varp_id":                        1,
	"ambient_sound_id":               1,
	"ambient_sound_ids":              3,
	"ambient_sound_retain":           1,
	"ambient_sound_distance":         1,
	"ambient_sound_change_ticks_min": 1,
	"ambient_sound_change_ticks_max": 1,
	"params":                         2,
	"a_bool_2111":                    3,
	"blocks_projectile":              3,
	"randomize_anim_start":           3,
}

var Queries = map[int]string{
	1: "SELECT * FROM %s WHERE %s == ? ORDER BY id",
	2: "SELECT * FROM %s WHERE %s LIKE '%%' || ? || '%%' COLLATE NOCASE ORDER BY id",
	3: "", // Should be unreachable
}
